---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: opscode-ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
suites:
  - name: default
    run_list:
      - recipe[thunr_chef_app_db::default]
      - recipe[minitest-handler]
    attributes:
  - name: test
    run_list:
      - recipe[thunr_chef_app_db::default]
      - recipe[minitest-handler]
    attributes: {
      mysql: {
        bind_address: '0.0.0.0'
      }
    }
    driver_config:
      network:
        - ["forwarded_port", {guest: 3306, host: 13306}]

settings:
  parallel: true
